### ISSUE TITLE
Does not work with LazyVim

### ISSUE THREAD

**Issue by prgres** [soulis-1256/eagle.nvim#17]
I am using the LazyVim setup I installed this plugin according to the docs. Despite being loaded, the plugin fails to display any content in the hover window motion as expected.

my config:

```lua
return {
  {
    "soulis-1256/eagle.nvim",
    -- opts = {},
    -- config = function(_, opts)
    --   require("eagle").setup(opts)
    -- end,
    -- config = true,
    -- init = function()
    --   vim.o.mousemoveevent = true
    -- end,
  },
}
```

I tried a various combination of configurations but I am not able to run it. Tested on files with python, terraform, and golang.

**Comment by soulis-1256** [comment]
Please read the Readme. I addressed there that you shouldn't use Lazy's properties. You should change the way you load my plugin according to my example.

**Comment by prgres** [comment]
I forgot to add that I have also set `vim.o.mousemoveevent = true` without Lazy properties without any luck

**Comment by prgres** [comment]
>Please read the Readme. I addressed there that you shouldn't use Lazy's properties. You should change the way you load my plugin according to my example.

As I said, I tried multiple ways starting with config from README but this did not work - then I tried to mess with Lazy properties (everything is commented out 🤷🏼 )

**Comment by soulis-1256** [comment]
Explain the parts of your config that are related to loading my plugin, following my readme instructions. You should be loading the plugin like this:
```lua
return {
  {
    "soulis-1256/eagle.nvim",
  },
}
```
and then inside your main init.lua (or the parent file that accepts the return value of your plugins file), do this:
```lua
require("eagle").setup({
-- override the default values found in config.lua
})

-- make sure mousemoveevent is enabled
vim.o.mousemoveevent = true
```

If you are 100% sure that's the way you load the plugin and the problem persists, then we can talk about your Neovim version, as right now it's tested on 0.9.4 and 0.9.5. Also, I have a debug mode that you can enable as a last resort, I will guide you through it if it comes to that.

**Comment by soulis-1256** [comment]
I'm closing the issue since some days have passed without response on your end. Feel free to message me on [Discord](https://discord.com/users/319490489411829761) or open a new issue (or re-open this one if possible) addressing what I talked about in my previous comment.
