### ISSUE TITLE
Neovim default right click menu dissapears on hover.

### ISSUE THREAD

**Issue by parishrutpandey** [soulis-1256/eagle.nvim#19]
Without plugin (expected):
![withoutplugin](https://github.com/soulis-1256/eagle.nvim/assets/69558696/cc9114b1-6f0f-4d64-ba8d-42914b0d45b1)
With plugin:
![withplugin](https://github.com/soulis-1256/eagle.nvim/assets/69558696/42011349-a783-453b-a4a3-d0cf0f19217a)

**Comment by soulis-1256** [comment]
Thank you for noticing. I knew this but I never considered that my plugin was causing it. Let me see if I can find the problem.

**Comment by soulis-1256** [comment]
I just pushed an update with a rather small change that should have fixed the problem. Please confirm this so I can close the issue.

**Comment by soulis-1256** [comment]
I'm closing the issue regardless, since there's no response on your end. Feel free to reopen if there's anything wrong.
