### ISSUE TITLE
Feat: Dynamically flip diagnostics and lspinfo order when displayed above/below row

### ISSUE THREAD

**Issue by GNRSN** [soulis-1256/eagle.nvim#23]
Thanks for the great plugin! Been looking for a combined diagnostics and hover UI since swapping to nvim. 

After about a week of usage I've found myself being confused when hovering an item with diagnostics, whilst actually looking for the lsp info. When the ui opens above the line the lsp-info is just next to the target, which I'm used to from previous hovers, but when it opens bellow the line, the lsp info is at the bottom, possibly quite a few lines down since diagnostic is always >= 4 rows high. 

I think flipping the sections dynamically would make the the hover more predictable/easy to read. 

I assume this would have to be configurable by a setting for users who prefer the existing behavior.

**Comment by soulis-1256** [comment]
@GNRSN Hi, can you provide an example? Ideally screenshots or even a quick video. I don't think what you described is supposed to be desired behavior.

**Comment by GNRSN** [comment]
Above cursor/line
<img width="805" alt="image" src="https://github.com/user-attachments/assets/c6633fa1-8490-45dc-b95b-ca11b8ea3efa">

Below cursor/line
<img width="821" alt="image" src="https://github.com/user-attachments/assets/80959554-a173-4ce9-bed8-fd046f183933">

The hover window contents are always "sorted" by diagnostic first and then lsp info. What I'm asking for is to "flip" these when positioned below so that is possible to expect the lsp-info closest to the cursor.

**Comment by GNRSN** [comment]
Here is a photobash of how I would have expeced the result to look:
<img width="968" alt="image" src="https://github.com/user-attachments/assets/3c54a330-e733-4d8b-bea3-22aee1ef7b03">

**Comment by soulis-1256** [comment]
Oh, I understand now. That should be as simple as adding a config option. I'll get to it soon.

**Comment by soulis-1256** [comment]
@GNRSN I think it's ready. Just add `order = 2` in your custom options. I added all four possible options, not just what you asked for.

**Comment by GNRSN** [comment]
@soulis-1256 Just tried it, amazing, thank you!
